// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Dashboard_UI

#include "../ui.h"

void ui_Screen_Loading_screen_init(void)
{
    ui_Screen_Loading = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Loading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Loading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Loading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Screen_Loading, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Screen_Loading, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_Image1 = lv_img_create(ui_Screen_Loading);
    lv_img_set_src(ui_Image1, &ui_img_rusolar_resized_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 313
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 150);

    ui_Container2 = lv_obj_create(ui_Screen_Loading);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 278);
    lv_obj_set_height(ui_Container2, 50);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 90);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Container2, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 30);
    lv_obj_set_height(ui_Spinner1, 30);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_NotConnected = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_NotConnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NotConnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NotConnected, 2);
    lv_obj_set_y(ui_NotConnected, -7);
    lv_obj_set_align(ui_NotConnected, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_NotConnected, "Not Connected");
    lv_obj_set_style_text_color(ui_NotConnected, lv_color_hex(0xBBBBBB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NotConnected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NotConnected, &ui_font_BarlowMedium20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
