// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Dashboard_UI

#include "../ui.h"

void ui_Screen_Dark_screen_init(void)
{
    ui_Screen_Dark = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Dark, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
