// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Dashboard_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen_Main
void ui_Screen_Main_screen_init(void);
lv_obj_t * ui_Screen_Main;
lv_obj_t * ui_RightArrow;
lv_obj_t * ui_LeftArrow;
lv_obj_t * ui_Container3;
lv_obj_t * ui_SpeedLabel;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_ExampleWhite;
lv_obj_t * ui_ExampleYellow;
lv_obj_t * ui_ExampleRed;
lv_obj_t * ui_PowerLevel;
lv_obj_t * ui_BatLevel;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image5;


// SCREEN: ui_Screen_Loading
void ui_Screen_Loading_screen_init(void);
lv_obj_t * ui_Screen_Loading;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_NotConnected;


// SCREEN: ui_Screen_Dark
void ui_Screen_Dark_screen_init(void);
lv_obj_t * ui_Screen_Dark;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_battery_full_dp_fill1_wght400_grad0_opsz[1] = {&ui_img_battery_full_20dp_fill1_wght400_grad0_opsz20_png};
const lv_img_dsc_t * ui_imgset_bolt_dp_fill1_wght400_grad0_opsz[1] = {&ui_img_bolt_20dp_fill1_wght400_grad0_opsz20_png};
const lv_img_dsc_t * ui_imgset_official_logo_square_[1] = {&ui_img_official_logo_square_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_Main_screen_init();
    ui_Screen_Loading_screen_init();
    ui_Screen_Dark_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_Main);
}
